sudo: required
dist: trusty
git:
  depth: 1
language:
- c
install:
- pwd
script:
- ./build.sh

deploy:
  provider: releases
  api_key:
    secure: HivKVk4jW7RQtnuIV1YEVZbjB4AjyH7wk/KLQOKG8b4remoHoGydeTg63RBgiM9m5TAkTEJCzDX6x5pLRu76JOx7UU508HQR2hZo9Z6mZaPdbxKTtVyW6EbqiM13TOvHIFISjhXvsf+RgHftKRRPhyTmLiZQpdOh3HuidSeZSAdxHG1c8HCbjRhMtUrUJrh3t6QnP3uIHNv2DnBnkA063zk/qlwe5zySISkOOUfeZ7JFfL8l4piJZ3ApcWgIL+nNoTSHC6Cb3pBESfx78WT81BFACfDSujq+HQKHxNKHqxZxGP/oMYZ3/+6tzxnFcsQghFExubG0COJePokZHvh2CHUxQxNQUlqRYIUy61KGYv7vElY+yJ3WNCrB9yE5pL8FwHvVnmdx3gNkI+Hc15GVPPIWWkrARCBk+WTONkM0uUeSRkNZj6QC1/te3q1wl77hu0z4prbf66ffR5yZVuAwa5D32DRtcRm6AyPcT0dCh6dGSbqxPGp1+zSqDnuuKumj+wsll+Lc5ewBM6p7gGvnR4KpzeaZteTmT81WehbocCOzGZBmFvcSCkoR+lUyiG/7t7BknI+fj29dWipYv6+PtSrBIBXioxhyGSf1g48/+2OkJ6qoqxWqqLQp1IeV5TyYEi8/+56Ze/fI7/KGL0+9nU4uto77o2nz2sbLhRplV1I=
  file:
    - "${TRAVIS_BUILD_DIR}/*.deb"
    - "${TRAVIS_BUILD_DIR}/build_wifi_deb/build/*.deb"
    - "${TRAVIS_BUILD_DIR}/build_wifi_deb/*.deb"
    - "${TRAVIS_BUILD_DIR}/linux-firmware-image-${KERNEL_VER}-${LOCALVERSION}_${KDEB_PKGVERSION}_armhf.deb"

  skip_cleanup: true
  on:
    tags: true
